server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #fasle表示自己不像自己注册
    fetch-registry: false #表示自己就是注册中心，不需要去检服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 单机
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/