server:
  port: 80


eureka:
  client:
    register-with-eureka: false #fasle表示自己不像自己注册
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 单机
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7001.com:7001/eureka/
feign:
  hystrix:
    enabled: true