server:
  port: 8081
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.uniview.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservice-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://47.104.208.82:5432/cloudDB01
    username: postgres
    password: admin_123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8081-hystrix
    prefer-ip-address: true


info:
  app:
    name: uniview-microservicecloud
  company:
    name: www.uniview.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$