server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app:
    name: uniview-microservicecloud
  company:
    name: www.uniview.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$
zuul:
  routes:
    mydept.serviceId: microservice-dept
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /uniview
